spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server.petclinic:9411
server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: false
    hostname: customers-service.petclinic
    instance-id: customers-service:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://discovery-server.petclinic:8761/eureka/
